apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devboard-intern
  namespace: devboard

rules:
- apiGroups: ["","apps","extensions"]
  resources: ["pods", "services", "endpoints", "deployment"]
  verbs: ["get","list"]