#Goal : To deploy the build images from ci steps once the ci workflow is succeded

name: CD

on:
  workflow_call:


jobs:
  deploy:
      runs-on: self-hosted
      steps:
        - name: Code Checkout 
          uses: actions/checkout@v7

        - name: Copy example into main env
          run: cp .env.example .env

        - name: Docker Login
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Deploy the containers with docker-compose
          run: |
            docker compose pull
            docker compose up -d