#Goal :- I have to ensure dependencies are up to date and no vulnerable dependencies and packages havve audited for Security


name: Dependency Scan

on:
  workflow_call:     #you can call this workflow before after any other workflow


jobs:

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.22 
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: Install Go Vulnecheck
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4

      - name: Run Go Vulnecheck
        run: govulncheck ./... > govulncheck-report.txt
        working-directory: backend
        continue-on-error: true  # Continue even if vulnerabilities are found

      - name: Upload Report to Artifacts
        if: always()  # Ensure the report is uploaded even if the previous step fails
        uses: actions/upload-artifact@v4
        with:
          name: job-report
          path: reports/go-vulncheck-report.txt
          retention-days: 7


      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20'  
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Run Dependency Audit
        run: npm audit
        working-directory: frontend
        
    