#Goal To tun the end to end DevSecOps CI/CD pipeline

name: DevSecOps


on:
  push:
    branches: [master]

jobs:

  #this is CI
  #Code stage with Shift Left
  code-quality:
    uses: ./.github/workflows/code-quality.yml


  secret-scanning:
    uses: ./.github/workflows/secret-scanning.yml


  dependency-scanning:
    uses: ./.github/workflows/dependency-scan.yml


  docker-scanning:
    uses: ./.github/workflows/docker-scans.yml
    secrets: inherit 

  sonar-qube:
    uses: ./.github/workflows/sonar-scan.yml
    secrets: inherit

  code-test:
    uses: ./.github/workflows/code-tests.yml

  push-to-docker:
    needs: [code-quality,secret-scanning,dependency-scanning,docker-scanning,sonar-qube,code-test]
    secrets: inherit
    uses: ./.github/workflows/docker-push.yml


#------CD---------


  deploy:
    needs: [push-to-docker]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit    
